name: Backend tests

on:
  pull_request:
    branches:
      - main
      - v1
  workflow_dispatch: {}

jobs:
  black-mypy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install poetry
          cd backend
          poetry install
      - name: Run mypy
        run: |
          cd backend
          poetry run mypy --config-file mypy.ini .
      - name: Run black
        run: |
          cd backend
          poetry run black --check .

  uvicorn-launch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install poetry
          cd backend
          poetry install
      - name: Run Uvicorn
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd backend
          timeout 10s poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl http://localhost:8000/health

  container-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build backend/Dockerfile
        run: |
          cd backend
          docker build -t backend .
      - name: Build backend/embedding/Dockerfile
        run: |
          cd backend
          docker build -t embedding -f embedding/Dockerfile .
